
## Fiducial Binomial MAD Visuals

```{r, echo=FALSE, warning = F, message = F}
library(ggplot2)
full_data = data.frame(P = NA, MAD = NA, parameter = NA, data_size = NA,
                       upper_p = NA, lower_p = NA)

for(name in list.files(path = "binData/")[-1]){
  temp_data = read.csv(paste("binData/",name, sep =""))[,-1]
  full_data = rbind(full_data, temp_data)
}
full_data = full_data[-which(is.na(full_data$P)),]
full_data$P = as.factor(full_data$P)
```

```{r, echo=FALSE, warning = F, message = F}
# All sizes MAD:
ggplot(full_data, aes(x = P, y = MAD, color = parameter)) + geom_boxplot() + facet_grid( data_size ~ .) + 
  ggtitle("Mean Difference; All Sizes") 

size = 10
my_data = full_data[which(full_data$data_size ==size),]
ggplot(my_data, aes(x = P, y = MAD, color = parameter)) + geom_boxplot() + 
  ggtitle(paste("Mean Difference; Data Size = ", size, sep="")) 

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "fiducial-n"),]
ggplot(my_data, aes(x = upper_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Fiducial Upper Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = upper_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Fiducial Upper Confidence Set; Data Size = ", size, sep="")) + xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "bayesian-n"),]
ggplot(my_data, aes(x = upper_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Bayesian Upper Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = upper_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Bayesian Upper Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "fiducial-n"),]
ggplot(my_data, aes(x = lower_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Fiducial Lower Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = lower_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Fiducial Lower Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "bayesian-n"),]
ggplot(my_data, aes(x = lower_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Bayesian Lower Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = lower_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Bayesian Lower Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")

size = 50
my_data = full_data[which(full_data$data_size ==size),]
ggplot(my_data, aes(x = P, y = MAD, color = parameter)) + geom_boxplot() + 
  ggtitle(paste("Mean Difference; Data Size = ", size, sep="")) 

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "fiducial-n"),]
ggplot(my_data, aes(x = upper_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Fiducial Upper Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = upper_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Fiducial Upper Confidence Set; Data Size = ", size, sep="")) + xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "bayesian-n"),]
ggplot(my_data, aes(x = upper_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Bayesian Upper Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = upper_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Bayesian Upper Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "fiducial-n"),]
ggplot(my_data, aes(x = lower_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Fiducial Lower Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = lower_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Fiducial Lower Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "bayesian-n"),]
ggplot(my_data, aes(x = lower_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Bayesian Lower Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = lower_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Bayesian Lower Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")


size = 100
my_data = full_data[which(full_data$data_size ==size),]
ggplot(my_data, aes(x = P, y = MAD, color = parameter)) + geom_boxplot() + 
  ggtitle(paste("Mean Difference; Data Size = ", size, sep="")) 

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "fiducial-n"),]
ggplot(my_data, aes(x = upper_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Fiducial Upper Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = upper_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Fiducial Upper Confidence Set; Data Size = ", size, sep="")) + xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "bayesian-n"),]
ggplot(my_data, aes(x = upper_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Bayesian Upper Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = upper_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Bayesian Upper Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "fiducial-n"),]
ggplot(my_data, aes(x = lower_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Fiducial Lower Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = lower_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Fiducial Lower Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")

my_data = full_data[which(full_data$data_size ==size & full_data$parameter == "bayesian-n"),]
ggplot(my_data, aes(x = lower_p, fill = P)) + geom_histogram() + 
  ggtitle(paste("Bayesian Lower Confidence Set; Data Size = ", size, sep=""))
ggplot(my_data, aes(x = lower_p, color = P)) + stat_ecdf() + 
  ggtitle(paste("Bayesian Lower Confidence Set; Data Size = ", size, sep=""))+ xlab("Nominal Coverage") + ylab("Empirical Coverage")
```